### ISSUE TITLE
Undo/Redo after clearing misses latest add

### ISSUE THREAD

**Issue by hooyushing** [AY2425S1-CS2103T-T15-2/tp#185]
Undo/Redo after clearing misses latest add

Steps to recreate:
1) Clear EduTuTu using `clear` command
2) execute `undo` command

Expected result: Full list of contacts before clear restored
Actual result: Latest added contact not restored

![Screenshot 2024-10-27 at 7 50 47 PM](https://github.com/user-attachments/assets/a8d9ebe8-9a66-4f26-92c7-905302aee455)
![Screenshot 2024-10-27 at 7 51 05 PM](https://github.com/user-attachments/assets/baf98ce1-8812-41b4-b91b-6df7f7ae11e9)

**Comment by sumomomomomo** [comment]
Found the issue in `setAddressBook` in `ModelManager.java`: `historicalAddressBook.save()` needs to be called after `resetData()`

Will open PR
