### ISSUE TITLE
Edit Command is able to allow duplication of person with different case (i.e. lowercase)

### ISSUE THREAD

**Issue by hooyushing** [AY2425S1-CS2103T-T15-2/tp#202]
To replicate bug:
1) Have a person named Tan in the addressbook, and another person with a random name
2) Edit the other person's name to "tan", with lowercase t. 

Expected outcome: Detects that the 2 names are the same and shows an error message
Actual outcome: Successful edit of person

![Screenshot 2024-10-29 at 12 21 18 AM](https://github.com/user-attachments/assets/4637990e-6b9b-4f8c-a19a-beb50d6d835e)

**Comment by sumomomomomo** [comment]
I think it should be allowed. Ie accept the user's command but with a warning

**Comment by sumomomomomo** [comment]
Closing as this is not a problem anymore after updating Name's equals method.
