### ISSUE TITLE
MarkPaid Feature Allows Future Dates for Payment Records

### ISSUE THREAD

**Issue by munhuikim** [AY2425S1-CS2103T-T15-2/tp#225]
<img width="1043" alt="스크린샷 2024-10-31 오전 6 21 45" src="https://github.com/user-attachments/assets/e1b0b42a-5323-4fc1-9f10-8962aad9fe1f">

Expected Behavior:
The MarkPaid feature should restrict the date to either the current date or a past date only, preventing future dates from being selected.

Actual Behavior:
The feature allows future dates to be recorded, which could lead to errors in payment tracking.

**Comment by sumomomomomo** [comment]
Out of scope. Better to grant the user this leniency imo.
