### ISSUE TITLE
Find Command only applies to 'm/' filter, ignoring '!m/' condition

### ISSUE THREAD

**Issue by munhuikim** [AY2425S1-CS2103T-T15-2/tp#226]
When using the find command with both m/ and !m/ filters with the same condition, it should ideally display the entire list (as both inclusion and exclusion of the same condition should cover all items). However, the find command currently only applies the m/ filter, ignoring the !m/ condition, leading to an incomplete or incorrect result.
![Uploading 스크린샷 2024-10-31 오전 6.33.38.png…]()
![Uploading 스크린샷 2024-10-31 오전 6.33.55.png…]()

**Comment by hooyushing** [comment]
Only allow n/, c/, m/, !m/ and n/ c/ as acceptable prefixes for find, no other combinations of prefixes for find will be allowed

**Comment by hooyushing** [comment]
Empty string after find prefix is also not permitted anymore
