### ISSUE TITLE
Inconsistent fee amounts allowed for the same class

### ISSUE THREAD

**Issue by munhuikim** [AY2425S1-CS2103T-T15-2/tp#227]
Expected Behavior:
The system should enforce a consistent fee amount for all students within the same class, or provide a prompt if there’s a valid reason for exceptions.

Actual Behavior:
The system allows different fee amounts to be recorded for students in the same class without any warnings, leading to inconsistencies.
![Uploading 스크린샷 2024-10-31 오전 6.38.14.png…]()

**Comment by sumomomomomo** [comment]
Realistically, eg, for private tutors, long time students could have a cheaper rate than newer students.
