### ISSUE TITLE
Class ID Should be recorded in capital letters for consistency

### ISSUE THREAD

**Issue by munhuikim** [AY2425S1-CS2103T-T15-2/tp#228]
Expected Behavior:
The system should automatically convert and store the Class ID in capital letters, regardless of the input case, ensuring uniformity across all records.

Actual Behavior:
The Class ID is recorded as entered, preserving lowercase letters if they were uploaded in lowercase, leading to inconsistent record-keeping.
![Uploading 스크린샷 2024-10-31 오전 6.42.13.png…]()

**Comment by sumomomomomo** [comment]
Potentially too restrictive for the user.
