### ISSUE TITLE
Undo Redo GUI not highlighted when command should be enabled

### ISSUE THREAD

**Issue by waihin26** [AY2425S1-CS2103T-T15-2/tp#232]
![Screenshot 2024-10-31 at 9 50 00 AM](https://github.com/user-attachments/assets/97d1c652-9752-43fb-8d48-c7d96968ec34)

When using GUI and mouse to undo redo, command is not available for use even tho on CLI it works (undo/redo)

**Comment by hooyushing** [comment]
Is a different command tho, one is for undo the copy and paste, one is for undo previous command

**Comment by sumomomomomo** [comment]
Out of scope.
