### ISSUE TITLE
[PE-D][Tester D] User Guide: Different Heading Formats for Method 1 and Method 2

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-2/tp#300]
Minor cosmetic bug found - "Method 1" and "Method 2" in Section 2.17 of User Guide are of different heading formats. See the top and bottom of the screenshot below.

![{24FF55F1-762F-4A42-B9CF-974587701A79}.png](https://raw.githubusercontent.com/lutfir-cpu/ped/main/files/44cca574-be6a-47c3-87a4-fed7976edf55.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: lutfir-cpu/ped#1

**Comment by waihin26** [comment]
Resolved
