### ISSUE TITLE
[PE-D][Tester C] Missing command in command summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-2/tp#304]
![image.png](https://raw.githubusercontent.com/ZweZeya/ped/main/files/67faab58-08c0-46f4-8f18-f6eeeb63d414.png)

The summary table here is missing the `unmarkpaid` command.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ZweZeya/ped#8

**Comment by waihin26** [comment]
Resolved
