### ISSUE TITLE
[PE-D][Tester C] Missing link for section 2.14 in table of contents in user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-2/tp#315]
![image.png](https://raw.githubusercontent.com/ZweZeya/ped/main/files/9ea941ed-48d5-4c16-89ac-5a5988c2265d.png)

The link does not work for section `2.14` (not clickable) but other links work fine (redirect the reader to the correct section).

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ZweZeya/ped#13

**Comment by waihin26** [comment]
Resolved
