### ISSUE TITLE
[PE-D][Tester C] Student details window does not show updated data

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-2/tp#319]
For `pie` and `bar` commands, the user guide clearly states that the data has to be updated before running the command, but this is not stated for `info`. Hence, the reader may expect a real-time data update of the pop-up window. For example, after the `info` window is opened, commands that mutate the data like `add`, `delete`, `edit`, etc will not cause the changes to be automatically reflected.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ZweZeya/ped#14

**Comment by waihin26** [comment]
Resolved
