### ISSUE TITLE
[PE-D][Tester C] Links in developer guide points to AB3

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-2/tp#332]
![Screenshot 2024-11-08 at 5.19.33 PM.png](https://raw.githubusercontent.com/ZweZeya/ped/main/files/90c5e19c-93fd-4486-9622-72f6ac57a085.png)

![Screenshot 2024-11-08 at 5.17.43 PM.png](https://raw.githubusercontent.com/ZweZeya/ped/main/files/f8e56f34-2fcc-43fc-a562-6394c7a34f15.png)

There are multiple links in the developer guide like the ones that I underlined that points to AB3 instead of Edututu.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: ZweZeya/ped#19

**Comment by waihin26** [comment]
Resolved
