### ISSUE TITLE
[PE-D][Tester E] User guide: Outdated screenshot

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-2/tp#335]
### Details
In the following screenshot, months paid is displayed as "(empty)" in the image:
![Screenshot 2024-11-08 at 5.39.13 PM.png](https://raw.githubusercontent.com/myrilla12/ped/main/files/a57ee7d7-215d-4f36-816c-69359b1872a3.png)

This is seen for multiple screenshots in page 13 onwards of the user guide. 

However, in the current application behaviour this is not seen:

![Screenshot 2024-11-08 at 5.40.35 PM.png](https://raw.githubusercontent.com/myrilla12/ped/main/files/74dd9664-09da-4ac2-be47-d48392cad14c.png)

### Suggested improvement
Update user guide screenshot.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: myrilla12/ped#13

**Comment by waihin26** [comment]
Resolved
