### ISSUE TITLE
[PE-D][Tester C] Weird formatting before use cases in developer guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-2/tp#345]
![Screenshot 2024-11-08 at 6.03.12 PM.png](https://raw.githubusercontent.com/ZweZeya/ped/main/files/af63cbea-01ef-427d-b002-90d68cec9b59.png)

There is a formatting issue at the start of the `Use cases` in the developer guide. There are 2 lines with nothing in between.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ZweZeya/ped#23

**Comment by waihin26** [comment]
Resolved
